"""Automatic graph optimization — static analysis for parallelization.

The :class:`AutoOptimizer` analyzes compiled graphs and automatically
detects independent execution paths, suggesting or applying parallel
fan-out edges.

Usage::

    from graphforge._optimizer import optimize, auto_parallelize, OptimizationReport

    report = optimize(compiled_graph, state_type)
    # report.independent_paths -> [[node_a, node_b], [node_c, node_d]]
    # report.parallelization_suggestions -> [...]

    # Or apply automatically:
    optimized = auto_parallelize(graph_builder, state_type)
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set, Tuple

from graphforge._graph import Graph, CompiledGraph
from graphforge._node import NodeKind
from graphforge._types import NodeName


# ---------------------------------------------------------------------------
# Optimization Report
# ---------------------------------------------------------------------------


@dataclass
class OptimizationReport:
    """Report generated by graph optimization analysis.

    Parameters
    ----------
    independent_paths:
        Groups of nodes that can be executed in parallel.
    parallelization_suggestions:
        Suggested fan-out edges (source, [targets]).
    unused_nodes:
        Nodes that are never reached from the entry point.
    bottleneck_nodes:
        Nodes that are on the critical path and could be parallelized.
    cycle_warning:
        Whether cycles were detected in the graph.
    """
    independent_paths: List[List[NodeName]] = field(default_factory=list)
    parallelization_suggestions: List[Tuple[NodeName, List[NodeName]]] = field(default_factory=list)
    unused_nodes: List[NodeName] = field(default_factory=list)
    bottleneck_nodes: List[NodeName] = field(default_factory=list)
    cycle_warning: bool = False

    def summary(self) -> str:
        """Return a human-readable summary of the report."""
        lines = ["OptimizationReport:"]
        if self.independent_paths:
            lines.append(f"  Independent paths: {len(self.independent_paths)}")
            for path in self.independent_paths:
                lines.append(f"    - {' → '.join(path)}")
        if self.parallelization_suggestions:
            lines.append(f"  Parallelization suggestions: {len(self.parallelization_suggestions)}")
            for src, targets in self.parallelization_suggestions:
                lines.append(f"    - {src} → [{', '.join(targets)}]")
        if self.unused_nodes:
            lines.append(f"  Unused nodes: {len(self.unused_nodes)} → {self.unused_nodes}")
        if self.bottleneck_nodes:
            lines.append(f"  Bottlenecks: {len(self.bottleneck_nodes)} → {self.bottleneck_nodes}")
        if self.cycle_warning:
            lines.append("  ⚠ Cycle detected in graph")
        return "\n".join(lines)


from dataclasses import dataclass, field


# ---------------------------------------------------------------------------
# Optimizer
# ---------------------------------------------------------------------------


class AutoOptimizer:
    """Static graph analyzer for optimization opportunities.

    Parameters
    ----------
    graph:
        The compiled graph to analyze.
    state_type:
        Optional state type for field-level dependency analysis.
    """

    def __init__(
        self,
        graph: CompiledGraph[Any],
        state_type: Optional[Any] = None,
    ) -> None:
        self._graph = graph
        self._state_type = state_type

    def analyze(self) -> OptimizationReport:
        """Run full optimization analysis on the graph.

        Returns
        -------
        An :class:`OptimizationReport` with findings.
        """
        report = OptimizationReport()

        # 1. Detect unused nodes (not reachable from entry point)
        reachable = self._reachable_nodes()
        for name in self._graph.nodes:
            if name not in reachable:
                report.unused_nodes.append(name)

        # 2. Detect independent paths (nodes with no transitive dependencies)
        deps = self._compute_dependencies()
        paths = self._find_independent_paths(deps, reachable)
        report.independent_paths = paths

        # 3. Generate parallelization suggestions
        suggestions = self._suggest_parallelization(paths, reachable)
        report.parallelization_suggestions = suggestions

        # 4. Detect bottlenecks (nodes with high betweenness centrality)
        bottlenecks = self._find_bottlenecks(deps, reachable)
        report.bottleneck_nodes = bottlenecks

        # 5. Cycle detection
        report.cycle_warning = self._has_cycle()

        return report

    def _reachable_nodes(self) -> Set[NodeName]:
        """Find all nodes reachable from the entry point via BFS."""
        entry = self._graph.entry_point
        visited: Set[NodeName] = set()
        queue = [entry]
        while queue:
            current = queue.pop(0)
            if current in visited or current == "__end__":
                continue
            visited.add(current)
            successors = self._graph.successors(current)
            for succ in successors:
                if succ is not None and succ != "__end__":
                    queue.append(succ)

            # Check conditional edges
            if hasattr(self._graph, "_conditionals") and current in self._graph._conditionals:
                for target in self._graph._conditionals[current].path_map.values():
                    if target != "__end__":
                        queue.append(target)

            # Check fan-out edges
            if hasattr(self._graph, "_fanout_map") and current in self._graph._fanout_map:
                for target in self._graph._fanout_map[current].targets:
                    queue.append(target)

        return visited

    def _compute_dependencies(self) -> Dict[NodeName, Set[NodeName]]:
        """Compute transitive dependencies for each node."""
        deps: Dict[NodeName, Set[NodeName]] = {}
        for name in self._graph.nodes:
            deps[name] = set()
            # A node depends on all its predecessors
            for other in self._graph.nodes:
                if other == name:
                    continue
                if self._has_path(other, name):
                    deps[name].add(other)
        return deps

    def _has_path(self, source: NodeName, target: NodeName) -> bool:
        """Check if there's a directed path from source to target."""
        visited: Set[NodeName] = set()
        queue = [source]
        while queue:
            current = queue.pop(0)
            if current in visited:
                continue
            visited.add(current)
            if current == target:
                return True
            successors = self._graph.successors(current)
            for succ in successors:
                if succ is not None and succ != "__end__":
                    queue.append(succ)
        return False

    def _find_independent_paths(
        self,
        deps: Dict[NodeName, Set[NodeName]],
        reachable: Set[NodeName],
    ) -> List[List[NodeName]]:
        """Find groups of independent nodes that can be parallelized."""
        # Simple approach: find nodes that have no dependency on each other
        paths: List[List[NodeName]] = []
        used: Set[NodeName] = set()

        for node in reachable:
            if node in used:
                continue
            # Find siblings (nodes that share the same dependency set)
            siblings = [n for n in reachable if n not in used and deps.get(n) == deps.get(node)]
            if len(siblings) > 1:
                # These siblings can be parallelized
                path = siblings
                paths.append(path)
                used.update(siblings)

        return paths

    def _suggest_parallelization(
        self,
        paths: List[List[NodeName]],
        reachable: Set[NodeName],
    ) -> List[Tuple[NodeName, List[NodeName]]]:
        """Generate parallelization suggestions from independent paths."""
        suggestions: List[Tuple[NodeName, List[NodeName]]] = []
        for path in paths:
            if len(path) < 2:
                continue
            # Find common predecessor
            for pred in reachable:
                if all(self._has_path(pred, n) for n in path):
                    suggestions.append((pred, path))
                    break
        return suggestions

    def _find_bottlenecks(
        self,
        deps: Dict[NodeName, Set[NodeName]],
        reachable: Set[NodeName],
    ) -> List[NodeName]:
        """Find nodes that appear on many dependency paths (bottlenecks)."""
        if len(reachable) < 3:
            return []
        # Count how many nodes depend on each node
        dep_counts: Dict[NodeName, int] = {}
        for node in reachable:
            count = sum(1 for n in reachable if node in deps.get(n, set()))
            dep_counts[node] = count

        # Nodes with high dependency counts are bottlenecks
        avg = sum(dep_counts.values()) / max(len(dep_counts), 1)
        return [n for n, c in dep_counts.items() if c > avg * 1.5 and c > 1]

    def _has_cycle(self) -> bool:
        """Simple cycle detection via DFS."""
        visited: Set[NodeName] = set()
        rec_stack: Set[NodeName] = set()

        def _dfs(node: NodeName) -> bool:
            if node in rec_stack:
                return True
            if node in visited or node == "__end__":
                return False
            visited.add(node)
            rec_stack.add(node)
            successors = self._graph.successors(node)
            for succ in successors:
                if succ is not None and succ != "__end__":
                    if _dfs(succ):
                        return True
            rec_stack.discard(node)
            return False

        return _dfs(self._graph.entry_point)


def optimize(
    graph: CompiledGraph[Any],
    state_type: Optional[Any] = None,
) -> OptimizationReport:
    """Analyze a compiled graph and generate optimization recommendations.

    Parameters
    ----------
    graph:
        The compiled graph to analyze.
    state_type:
        Optional state type for field-level dependency analysis.

    Returns
    -------
    An :class:`OptimizationReport` with optimization findings.

    Examples
    --------
    .. code-block:: python

        from graphforge._optimizer import optimize

        report = optimize(compiled)
        print(report.summary())

        if report.independent_paths:
            print(f"Can parallelize {len(report.independent_paths)} paths")
    """
    optimizer = AutoOptimizer(graph, state_type=state_type)
    return optimizer.analyze()


def auto_parallelize(
    graph: Graph,
    state_type: Optional[Any] = None,
) -> Graph:
    """Analyze a graph builder and automatically add fan-out edges for
    independent execution paths.

    Parameters
    ----------
    graph:
        The mutable graph builder. Nodes must already be registered.
    state_type:
        Optional state type for dependency analysis.

    Returns
    -------
    The same ``Graph`` builder with optimized edges added.

    Examples
    --------
    .. code-block:: python

        builder = Graph[MyState]()
        builder.add_node("a", fn_a).add_node("b", fn_b).add_node("c", fn_c)
        builder.add_edge("a", "b").add_edge("a", "c")
        builder.set_entry_point("a")

        # Auto-optimize: detects b and c are independent
        from graphforge._optimizer import auto_parallelize
        optimized = auto_parallelize(builder, MyState)
        # Now b and c will run in parallel
    """
    compiled = graph.compile(state_type=state_type)
    report = optimize(compiled, state_type=state_type)

    for source, targets in report.parallelization_suggestions:
        graph.add_fanout(source, targets)

    return graph


__all__ = [
    "AutoOptimizer",
    "OptimizationReport",
    "auto_parallelize",
    "optimize",
]
